import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service — ReviewPilot AI",
};

export default function TermsPage() {
  return (
    <main className="mx-auto max-w-3xl px-6 py-16">
      <h1 className="text-3xl font-bold text-slate-900">Terms of Service</h1>
      <p className="mt-2 text-sm text-slate-500">Last updated: August 2, 2026</p>

      <div className="prose prose-slate mt-10 max-w-none">
        <p>
          These Terms of Service (&quot;Terms&quot;) govern your access to and
          use of ReviewPilot AI (&quot;ReviewPilot AI,&quot; &quot;we,&quot;
          &quot;us,&quot; or &quot;our&quot;), including our website and
          dashboard (together, the &quot;Service&quot;). By creating an
          account or using the Service, you agree to these Terms. If you are
          using the Service on behalf of a business, you represent that you
          have authority to bind that business, and &quot;you&quot; refers
          to that business.
        </p>

        <h2>1. The Service</h2>
        <p>
          ReviewPilot AI monitors reviews posted about your business on
          platforms you connect (such as Google Business Profile), generates
          draft replies using an AI language model based on information you
          provide about your business&apos;s voice and preferences, and lets
          you approve, edit, or skip each draft. On plans where autopilot is
          available and you have enabled it, drafts for reviews rated 4 or 5
          stars may be posted automatically; reviews rated 1–3 stars are
          never posted automatically under any circumstance and always
          require your explicit approval.
        </p>

        <h2>2. Your account and connected platforms</h2>
        <p>
          You are responsible for the accuracy of the information you provide
          during setup, for maintaining the security of your account
          credentials, and for the content of any reply you approve or that
          is posted through autopilot. When you connect a third-party
          platform (e.g., Google Business Profile, Facebook Pages) via
          OAuth, you authorize us to access that platform&apos;s API on your
          behalf solely to retrieve reviews and post approved replies. You
          may revoke this access at any time, either from the third-party
          platform&apos;s own settings or from within ReviewPilot AI.
        </p>

        <h2>3. AI-generated content</h2>
        <p>
          Reply drafts are generated by an AI language model and are
          provided as suggestions. You are solely responsible for reviewing
          and, where applicable, editing any draft before it is approved or
          posted, including where autopilot is enabled. We do not guarantee
          that any draft is accurate, appropriate, or compliant with any
          particular law or regulation applicable to your business or
          industry, and you should apply your own judgment, particularly for
          regulated industries (e.g., healthcare, dental, or medical
          aesthetics) where specific disclosure or privacy rules may apply
          to public communications.
        </p>

        <h2>4. Fees and billing</h2>
        <p>
          Paid plans are billed in advance on a monthly or annual basis
          through our payment processor, Stripe. Trials require a valid
          payment method but will not be charged until the trial period
          ends, unless you cancel first. You may cancel at any time from
          your account&apos;s billing settings; cancellation takes effect at
          the end of the current billing period, and we do not provide
          partial-period refunds except where required by law.
        </p>

        <h2>5. Acceptable use</h2>
        <p>
          You agree not to use the Service to post content that is
          unlawful, defamatory, harassing, or that misrepresents a review or
          reply as coming from someone other than your business. You agree
          not to attempt to access another business&apos;s account or data,
          reverse-engineer the Service, or use the Service in a way that
          violates the terms of any connected third-party platform (such as
          Google&apos;s or Meta&apos;s developer policies).
        </p>

        <h2>6. Termination</h2>
        <p>
          You may stop using the Service and cancel your account at any
          time. We may suspend or terminate your access if you materially
          breach these Terms, misuse the Service, or if required to comply
          with a connected platform&apos;s policies (for example, if Google
          or Meta revokes API access related to your account).
        </p>

        <h2>7. Disclaimers and limitation of liability</h2>
        <p>
          THE SERVICE IS PROVIDED &quot;AS IS&quot; WITHOUT WARRANTIES OF ANY
          KIND, EXPRESS OR IMPLIED. TO THE MAXIMUM EXTENT PERMITTED BY LAW,
          REVIEWPILOT AI WILL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, OR
          CONSEQUENTIAL DAMAGES, OR FOR THE CONTENT OF ANY REPLY YOU APPROVE
          OR THAT IS POSTED VIA AUTOPILOT, AND OUR TOTAL LIABILITY FOR ANY
          CLAIM RELATING TO THE SERVICE WILL NOT EXCEED THE FEES YOU PAID US
          IN THE THREE MONTHS PRECEDING THE CLAIM.
        </p>

        <h2>8. Changes to these Terms</h2>
        <p>
          We may update these Terms from time to time. If we make material
          changes, we will notify you by email or through the Service before
          the changes take effect. Continued use of the Service after
          changes take effect constitutes acceptance of the updated Terms.
        </p>

        <h2>9. Governing law</h2>
        <p>
          These Terms are governed by the laws of the State of Delaware,
          United States, without regard to conflict-of-laws principles.
        </p>

        <h2>10. Contact</h2>
        <p>
          Questions about these Terms can be sent to{" "}
          <a href="mailto:pmcgrew82@gmail.com">pmcgrew82@gmail.com</a>.
        </p>
      </div>
    </main>
  );
}
